#!/bin/bash

#Submit this script with: sbatch thefilename

#SBATCH -t 96:00:00   # walltime
#SBATCH -N 1   # number of nodes in this job
#SBATCH -n 16   # total number of processor cores in this job
#SBATCH -J sim1   # job name
#SBATCH --mail-user=ajsage@iastate.edu   # email address
#SBATCH --mail-type=BEGIN
#SBATCH --mail-type=END
#SBATCH --mail-type=FAIL

# Load R module
module load parallel/20160422
module load r
module load r-partykit

R CMD BATCH Sim1_script.R

exit

